readme.md, source/index.ts, source/utils.ts, test.ts
This will allow to check any url for GitHub URLs
e.g
```js
isRepoDiscussionList(new URL(document.referref))
isRepoDiscussionList(window.location)
```
Blocks https://github.com/sindresorhus/refined-github/pull/2974
=> Accept a URL parameter

index.ts
Follows https://github.com/sindresorhus/refined-github/pull/3103#issuecomment-630157541
=> Add `canUserEditOrganization` Rename `isRepoWithAccess` to `canUserEditRepo`

index.ts
As per https://github.com/sindresorhus/refined-github/pull/3105#discussion_r427454967
=> Add `isEmptyRepo`

index.ts
Re https://github.com/sindresorhus/refined-github/issues/3182
=> Exclude `isConflict` from `isPR`

index.ts
As discussed in https://github.com/fregante/github-url-detection/pull/17#issuecomment-650622429.
=> Drop deprecated functions

index.ts, package.json
=> Fix `isRepoRoot`

index.ts, package.json, test.ts
Does not follow https://github.com/sindresorhus/refined-github/pull/3314#discussion_r449908749 😄 
`isPRCommit404` exists. I need the file 404
=> Add `isPRFile404`

index.ts
Fixes #24 
Fixes https://github.com/sindresorhus/refined-github/issues/3393
=> Clarify and fix `isRepoRoot`

index.ts
=> Fix relative URLs in getRepoURL

index.ts
=> Drop `Page` from `isSingleTagPage` and `isActionPage`

index.ts
Test on https://github.com/A?tab=overview&from=2020-08-01&to=2020-08-31
=> Add overview tab to `isUserProfileMainTab`

.github/workflows/demo.yml, .github/workflows/publish.yml, demo/.gitignore, demo/package-lock.json, demo/package.json, demo/public/global.css, demo/public/index.html, demo/rollup.config.js, demo/src/App.svelte, demo/src/main.ts, demo/tsconfig.json, package.json, readme.md
=> Add live demo

index.ts
=> Add `HTMLAnchorElement` as a type

.github/workflows/ci.yml, .github/workflows/demo.yml, .github/workflows/esm-lint.yml
Follows https://github.com/sindresorhus/project-ideas/issues/116 using https://github.com/fregante/ghatemplates#esm-lint
=> Meta: Add `esm-lint`

index.ts
- Include `isSingleGist` in `hasComments`
example URL:
- https://gist.github.com/KennethTsang9286/63744c422e267fd9f4c4b94ec8a179f6
=> Include `isSingleGist` in `hasComments`

index.ts
Fixes https://github.com/fregante/github-url-detection/issues/53
Fixes https://github.com/sindresorhus/refined-github/issues/3743
=> Report the correct repo URL even if GitHub lies

index.ts
https://github.com/organizations/npmhub/repositories/new
@fregante I don't know regex that well so I am not sure if this is correct
=> Add support for new organization repo to `isNewRepo`

index.ts
Will be used in https://github.com/sindresorhus/refined-github later.
=> Add `isRepoWiki `

index.ts
Closes #68 
I hope I got it right (I used `isEditingFile` as a basis).
=> Add `isNewFile`

index.ts
=> Include `/user/repo/labels/<label>` in `isRepoIssueList`

index.ts
Closes #76
you want another one for `is500` and  `isPasswordConfirmation` together?
=> Add `isPasswordConfirmation`

index.ts
Closes https://github.com/fregante/github-url-detection/issues/78
Closes https://github.com/sindresorhus/refined-github/pull/4348
Fixes https://github.com/sindresorhus/refined-github/issues/4342
Related to https://github.com/fregante/github-url-detection/pull/59
=> Include discussions in `hasRichTextEditor`

index.ts
You can test on https://github.com/npmhub (I tested by my own org)
=> Fix `canUserEditOrganization`

index.ts
As Per https://github.com/sindresorhus/refined-github/pull/4534#issuecomment-878059232
=> Rename `canUserEditOrganization` to `isUserTheOrganizationOwner`

index.ts
New release page has a rich text editor.
Closes https://github.com/sindresorhus/refined-github/issues/4693
=> Add `isNewRelease` to `hasRichTextEditor`

index.ts
This will be used in sindresorhus/refined-github#4820.
Also since the deletion page shares many aspects with `isEditingFile`, I wonder should we create a function including both of them or just merge `isDeletingFile` into it.
=> Add `isDeletingFile`

index.ts
See https://github.com/refined-github/refined-github/pull/4995#discussion_r737711276
=> Add `isReleases` and `isTags`

.github/workflows/esm-lint.yml, index.ts, package-lock.json, package.json, test.ts, tsconfig.json
Not done:
- update parcel to v2
- attempt to replace rollup with parcel too
=> Update dev dependencies and other meta fixes

demo/App.svelte, demo/index.html, index.ts, package.json, readme.md, test.ts
=> Transfer repo to `refined-github` organization

index.ts
- [`isRepoSearch`](https://github.com/refined-github/refined-github/search?q=github)
- [`isGlobalSearchResults`](https://github.com/search?q=org%3Arefined-github+github&type=code)
=> Add search pages to `hasCode`

index.ts
Planning to be used in https://github.com/refined-github/refined-github/pull/5545
=> Add `isGistRevision`

.github/workflows/demo.yml, .gitignore, demo/App.svelte, demo/global.css, demo/index.html, package-lock.json, package.json, vite.config.js
Tired of dealing with its bugs. Updating to v2 had some error so it's easier to replace it.
=> Replace Parcel with Vite

index.ts, readme.md
- Together with #136 
- Suggested in #133
=> Replace "Conversation" with "IssueOrPR" for clarity

index.ts
- Closes https://github.com/refined-github/github-url-detection/issues/133#issuecomment-1193116951
=> Rename `isOrganizationDiscussion` to `isTeamDiscussion`

.github/workflows/demo.yml, .npmrc, package-lock.json, package.json
- Resolves #160 
- Blocked by https://github.com/vitejs/vite/issues/10735
- Previously broken by https://github.com/npm/cli/issues/6235#event-8748593766
=> Update dev dependencies

index.ts
Addresses https://github.com/refined-github/refined-github/pull/6488#discussion_r1161588102
No idea why I mentioned `main`, doesn't seem necessary
Test: https://github.com/refined-github/refined-github/compare/main...automated-selector-testing
=> Fix `isBlank` false positives

index.ts
- Fixers https://github.com/refined-github/github-url-detection/issues/152
=> Restore `isOrganizationRepo`

index.ts
Fixes https://github.com/refined-github/github-url-detection/issues/168
=> Remove `isSingleTag` from `isReleasesOrTags`
