refined-github/github-url-detection

.github/workflows/npm-publish.yml

I thought that using GitHub’s suggested workflow would be enough to automate publishing, but it's incomplete.
Creating a Release online is not enough, I'd still have to run `npm version a.b.c && git push --follow-tags`, which defeats the purpose of this workflow.
However perhaps this can be built on somehow.

Automate publishing

---

index.ts
test.ts

Extracted from https://github.com/sindresorhus/refined-github/pull/3233.

Add `isPRCommit404` detection

---

index.ts

As per https://github.com/sindresorhus/refined-github/pull/3261#discussion_r443263751

Add `isRepoHome`

---

index.ts
readme.md

Closes #14.
Note that I didn't touch this one, as it actually should refer to `discussion`s:
https://github.com/fregante/github-url-detection/blob/0c856d2ccc11772a1178bd3451c1d3cf4f55aaa0/index.ts#L140-L145

Rename `discussion` → `conversation` 

---

index.ts

Detect `isRepoRoot` on branches with slashes

---

index.ts

This should improve support of `aNyCaSe/RePos` across the board

Use canonical URL in `utils.getRepoURL`

---

package.json

Testing this in https://github.com/sindresorhus/refined-github/pull/3581
It appears to work. Is this a breaking change?

Improve ES-Node compatibility with exports

---

index.ts

Rename `isAction` to `isMarketplaceAction`

---

index.ts

- add `isRepliesSettings`
- improve `hasRichTextEditor`
Test url:
https://github.com/settings/replies
https://github.com/settings/replies/:id/edit

Add `isRepliesSettings` and include it in `hasRichTextEditor`

---

index.ts
package.json
test.ts

Initially added in Refined GitHub, I think we can bring this over, unify it and deprecate any other function.
The 2 functions aren't mapped exactly to `getRepositoryInfo`. Here are the differences:
- `getRepoURL` did not actually check `isRepo`, so it would return `'settings'` if you were on `https://github.com/settings`
- `getRepoPath` did not use the canonical URL, however this probably isn't much of an issue generally
I need to ensure that this doesn't impact the current usage in RGH

Replace `getRepoURL` and `getRepoPath` with `getRepositoryInfo`

---

index.ts

This PR fixes `canUserEditRepo` so it can be used in https://github.com/sindresorhus/refined-github/pull/3783.
See https://github.com/sindresorhus/refined-github/pull/3840#issue-545224656 for the explanation behind this change.

Fix `canUserEditRepo`

---

index.ts

Add `isDiscussionList` and `isDiscussion`

---

index.ts

Add `isUserSettings` detector.
Test url:
https://github.com/settings
btw. the live demo is super helpful 👏

Add `isUserSettings`

---

index.ts

This can be used in sindresorhus/refined-github#4463 and sindresorhus/refined-github#4467.
Very interestingly, it seems you can actually create a page named `_new` or `_edit`, but you can't view it (only edit), so this should be safe.

Add `isNewWikiPage` and `isEditingWikiPage`

---

index.ts

Refined GitHub is not guaranteed to work when the user is logged out, but this package doesn't have to have the same limitation.

Don't throw error in `getUsername` when logged out

---

index.ts

Context: https://github.com/sindresorhus/refined-github/issues/4472
Possible improvements:
Possible "better meta tag" ideas
- twitter:title has `- overview` in the user, but it doesn't sound super safe
- analytics-location sounds great

Use faster detections for user profiles

---

index.ts

See https://github.com/refined-github/refined-github/pull/4986#issuecomment-954238853
Perhaps rename `isProject` to `isSingleProject`?

Add `isProjects`

---

index.ts
tsconfig.json

Though very rare, it is possible to have multiple ~~leading and trailing~~ 
successive slashes in `pathname`.

Trim all duplicate slashes

---

index.ts

closes https://github.com/fregante/github-url-detection/issues/98

Detect is404 even if logged out

---

index.ts

Reason: both kind of pages are almost identical ("editing something").
While both are frequently used together, sometimes `isNewFoo` is easily left out since it's a special case that doesn't matter most of the time.
~~To replicate the old behavior of `isEditingFoo`, use `isEditingFoo() && !isNewFoo()`.~~
We need some utils to check for these pages at the same time.
Changes:
- Add `hasFileEditor`: `isEditingFile`, `isNewFile` and `isDeletingFile`
- Add `hasReleaseEditor`: `isEditingRelease` and `isNewRelease`
- Add `hasWikiPageEditor`: `isEditingWikiPage` and `isNewWikiPage`
- `hasRichTextEditor` checks for `hasReleaseEditor` instead of `isEditingRelease`

Add `hasFooEditor`

---

index.ts

These are not profiles:
- `<username>.png`
- `<username>.keys`
- `<username>.gpg`
- `<username>.atom` / `<username>.private.atom`

Exclude pathname with dot in `isProfile`

---

index.ts

Commit URLs can end with `.diff` or `.patch`, but they are not actually commits.
Note: there are similar suffixes for other types page as well:

Tighten `isCommit` and `isPRCommit` pattern

---

index.ts

The combination of `isCommit`, `isCompare` and `isPRFiles` is used a lot in Refined GitHub (for example, [`easy-toggle-files`](https://github.com/refined-github/refined-github/blob/c9d133547f45321c28fb7ddb35ffc08189c9082e/source/features/easy-toggle-files.tsx#L23-L25) and [`more-file-links`](https://github.com/refined-github/refined-github/blob/c9d133547f45321c28fb7ddb35ffc08189c9082e/source/features/more-file-links.tsx#L37-L39)). Adding them as a group so it remembers which pages have a list of files for us.

Add `hasFiles`

---

.github/workflows/demo.yml

[Commits made in the `gh-pages` branch are also counted as contributions](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile#commits), however this is not the case here since it's committed by bots actually.
@fregante if you don't care about it, I would like to mark those commits' author as bot.

Meta: Mark demo commit author as bot

---

index.ts

Resolves #100 
Example URLs:
- [Empty milestone](https://github.com/fish-shell/fish-shell/milestone/30)
- [Repo taken down by GitHub](https://github.com/fastai/fastmac)
- [Deleted issue](https://github.com/refined-github/refined-github/issues/2821)

Add `isBlank`

---

index.ts

Despite being called "Compare", this page type is more like a crossover between `isCommit` and `isGistRevision`, which means [`easy-toggle-files`](https://github.com/refined-github/refined-github/blob/main/source/features/easy-toggle-files.tsx) can support it when this get merged.

Add `isCompareWikiPage`

---

index.ts

Really this should be renamed to `isClosedConversation` but...

Add `isClosedConversation`

---

index.ts

Reverts this PR and instead ensures that `isClosedPR`, `isOpenPR`, etc only match PRs:
- https://github.com/refined-github/github-url-detection/pull/120

Ensure `is[Status]PR` only matches PRs and not issues

---

index.ts
package-lock.json
package.json

- Close https://github.com/refined-github/github-url-detection/issues/117
- Close https://github.com/refined-github/github-url-detection/issues/80

Improve Gist detection; exclude Gist profiles from `isProfile`

---

index.ts

- Closes https://github.com/refined-github/github-url-detection/issues/119
- More details in https://github.com/refined-github/refined-github/issues/5739#issuecomment-1170041988
cc @cheap-glitch 
BREAKING CHANGE
Refined GitHub will need to:
- replace most of its `isRepo` calls with `isRepoSearch`
- drop explicit `isRepoSearch` calls like `include: [isRepo, isRepoSearch]`, if any

Include Repo Search pages in `isRepo`; add `hasRepoHeader`

---

.github/workflows/esm-lint.yml
package.json

`vite build` does not build the types (and nukes `distribution` folder before building, so order matters 😅), so the published module is missing types:
https://github.com/refined-github/github-url-detection/runs/7555734222?check_suite_focus=true#step:7:19

Fix type publishing

---

index.ts

I just remembered, you can't follow yourself 🥲 so this time we are checking if the Stars tab is there.
I also tested the feature myself and learned it doesn't affect yourself (apparently). 
Test URL:
- A private user profile: https://github.com/Centril
- A public user profile, with no stars (to demonstrate the Stars tab is still shown for them): https://github.com/examplew

Fix `isPrivateUserProfile` false positive on `isOwnUserProfile`

---

index.ts

To be used in Refined GitHub (I think there may be several features could benefit from this)
I wonder why we didn't have this (until now)
Test URL: here

Add `isPublicRepo`

---

.github/workflows/ci.yml
index.ts
package-lock.json
package.json

- For https://github.com/refined-github/refined-github/issues/5485

Add support for Organization Discussions

---

index.ts

**Description**
- The changes update the `isPublicRepo` method to use `octolytics-dimension-repository_public` meta tag.
- Fixes [#151](https://github.com/refined-github/github-url-detection/issues/151).
**Tests with refined-github extension** 
- Previous implementation produced an minor issuse.
- **After changes**, test with public repo
- test with a private repo

Earlier detection for `isPublicRepo`

---

demo/App.svelte
demo/parse-url.js

- Closes #150
- Dynamically links the URL field to the `url` parameter
- https://deploy-preview-163--preview-for-github-url-detection.netlify.app/?url=http%3A%2F%2Fgist.github.com
- When the field is empty, the `url` parameter is dropped and the hardcoded default is picked up
- https://deploy-preview-163--preview-for-github-url-detection.netlify.app/
- Drops the standard origin from the parameter to keep the URL short (no `https://github.com`)
- https://deploy-preview-163--preview-for-github-url-detection.netlify.app/?url=%2Ffregante
- Only shows and accepts full URLs in the field

Allow permalinks in demo

---

collector.ts
demo/Detections.svelte
demo/Index.svelte
demo/detections.html
demo/detections.js
demo/index.js
demo/vite.config.ts

- For https://github.com/refined-github/refined-github/issues/5860
- [/detections.html](https://deploy-preview-164--preview-for-github-url-detection.netlify.app/detections.html)
- [/detections.html#isMilestoneList](https://deploy-preview-164--preview-for-github-url-detection.netlify.app/detections.html#isMilestoneList)

Add detections list page

---

.github/workflows/npm-publish.yml
index.ts
test.ts

We have these detections:
- isUserProfileMainTab
- isUserProfileRepoTab
- isUserProfileStarsTab
- isUserProfileFollowersTab
- isUserProfileFollowingTab
Which nowadays are unnecessarily specific since repository lists are similar in DOM, and will only get more similar (HOPEFULLY):
- https://github.com/fregante?tab=repositories
- https://github.com/orgs/refined-github/repositories
For the same reason I'm not adding an org-specific detection.
I haven't merged this yet to make sure I choose the right name here. I think `*Tab` was the wrong choice because:
- we don't have ~~`isRepoSettingsTab`~~ but `isRepoSettings` 
- etc
We can rename those separately, potentially deprecate `isUserProfileRepoTab` completely.

Add `isProfileRepoList`

---

index.ts

The new discussion page will exist in the repo and org, e.g.:
* https://github.com/withastro/roadmap/discussions/new?category=proposal
* https://github.com/orgs/community/discussions/new?category=pull-requests
And must excluded new discussion choose page, e.g.:
* https://github.com/orgs/reading-together/discussions/new/choose
Solved: #175

Add `isNewDiscussion` and add it to `hasRichTextEditor`

---

index.ts

Exclude special `search` URLs from `isRepoRoot` and `isRepoHome`

---

index.ts
test.ts

- `is404()` can not detecting new 404 pages
- https://github.com/fregante/GhostText/tree/3cacd7df71b097dc525d99c7aa2f54d31b02fcc8/chrome/scripts/InputArea
- https://github.com/refined-github/refined-github/blob/some-non-existent-ref/source/features/bugs-tab.tsx
- related: 
- https://github.com/refined-github/refined-github/issues/6413

Add `isFile404`

---

.github/workflows/ci.yml
collector.ts
index.test.ts
package-lock.json
package.json
tsconfig.json

Followup to:
- https://github.com/refined-github/github-url-detection/pull/129
- https://github.com/refined-github/github-url-detection/pull/135
AVA:
```
❯ time npx ava
14106 tests passed
________________________________________________________
Executed in    6.91 secs    fish           external
usr time    7.27 secs   93.00 micros    7.27 secs
sys time    0.91 secs  495.00 micros    0.91 secs
```
Bun:
```
14106 pass
0 fail
Ran 14106 tests across 1 files. [518.00ms]
```
Welp 😅

Replace AVA with bun:test

---

index.ts

Refined GitHub does not support logged out users, but a couple of features are troublesome (e.g. `locked-issue` will mark all issues as locked when logged out) so this check can be useful.

Add `isLoggedIn`

---

index.ts
package.json

Drops:
- isClosedPR
- isClosedIssue
- isOpenPR
No need to be that specific. These checks are best used together with more specific checks, like `isPR` or `isPRFiles`, they don't need to be super specific.
Also fixes https://github.com/refined-github/github-url-detection/pull/201/files#r1835622282

Refactor conversation state detections

---

.github/workflows/demo.yml
index.test.ts
index.ts
package.json

Fixes https://github.com/refined-github/github-url-detection/issues/189

Fix `isRepoRoot`

---

index.test.ts
index.ts

- For https://github.com/refined-github/refined-github/issues/8304

Add `isRepoGitObject`

---

index.ts

Fix this and then update `no-modals` feature.

 `isProject` - Add support for organization projects

---

index.ts

For: https://github.com/refined-github/refined-github/issues/8388

Add `isFork`
